name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  notion_db_sdk:
    path: ..

dev_dependencies:
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: main
