name: notion_db_sdk
description: A type-safe SDK for Notion APIs, which focuses on raw data, ignoring style elements, page blocks etc. and providig an idiomatic Dart interface.
homepage: https://github.com/Yogi-7y/notion-db-sdk
repository: https://github.com/Yogi-7y/notion-db-sdk
issue_tracker: https://github.com/Yogi-7y/notion-db-sdk/issues
license: MIT
version: 0.2.0

environment:
  sdk: ^3.4.0

dependencies:
  core_y: ^0.2.0
  meta: ^1.12.0
  network_y: ^0.1.1

dev_dependencies:
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: main
  mocktail: ^1.0.4
  test: ^1.24.0
