name: notion_db_sdk
description: A type-safe structured way to interact with Notion APIs.
homepage: https://github.com/Yogi-7y/notion_db_sdk
repository: https://github.com/Yogi-7y/notion_db_sdk
issue_tracker: https://github.com/Yogi-7y/notion_db_sdk/issues
license: MIT
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  core_y: ^0.1.0
  meta: ^1.12.0
  network_y: ^0.0.4+3

dev_dependencies:
  lints_y:
    git:
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: main
  mocktail: ^1.0.4
  test: ^1.24.0
