name: notion_db_sdk
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: ^3.4.0

dependencies:
  core_y: ^0.0.4+1
  meta: ^1.12.0
  network_y: ^0.0.3+3


dev_dependencies:
  lints_y:
    git: 
      url: https://github.com/Yogi-7y/Project-Y
      path: packages/lints
      ref: lints_v1.0.1
  mocktail: ^1.0.4
  test: ^1.24.0
